"""Add email_signature to settings

Revision ID: 0d49474106c3
Revises: 77dea5d964eb
Create Date: 2026-02-13 19:08:59.426700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d49474106c3'
down_revision: Union[str, Sequence[str], None] = '77dea5d964eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('report_email_subject_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('report_email_body_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('invoice_email_subject_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('invoice_email_body_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('report_invoice_email_subject_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('report_invoice_email_body_template', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('email_signature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'email_signature')
    op.drop_column('settings', 'report_invoice_email_body_template')
    op.drop_column('settings', 'report_invoice_email_subject_template')
    op.drop_column('settings', 'invoice_email_body_template')
    op.drop_column('settings', 'invoice_email_subject_template')
    op.drop_column('settings', 'report_email_body_template')
    op.drop_column('settings', 'report_email_subject_template')
    # ### end Alembic commands ###
