"""add claimant first/last name

Revision ID: 163eeb7af236
Revises: 36f30e4e8068
Create Date: 2026-01-29 13:19:14.219109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '163eeb7af236'
down_revision: Union[str, Sequence[str], None] = '36f30e4e8068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('claimant_first_name', sa.String(length=255), nullable=True))
    op.add_column('claim', sa.Column('claimant_last_name', sa.String(length=255), nullable=True))
    # Backfill from legacy claimant_name (best-effort).
    # Handles:
    #  - "Last, First" -> last="Last", first="First"
    #  - "First Last"  -> last="Last", first="First"
    #  - "Single"      -> last="Single", first=NULL
    op.execute(
        sa.text(
            """
            UPDATE claim
            SET
              claimant_first_name = CASE
                WHEN claimant_first_name IS NOT NULL AND btrim(claimant_first_name) <> '' THEN claimant_first_name
                WHEN claimant_name IS NULL OR btrim(claimant_name) = '' THEN NULL
                WHEN position(',' in claimant_name) > 0 THEN btrim(split_part(claimant_name, ',', 2))
                WHEN array_length(regexp_split_to_array(btrim(claimant_name), '\\s+'), 1) >= 2 THEN
                  array_to_string(
                    (regexp_split_to_array(btrim(claimant_name), '\\s+'))[1:array_length(regexp_split_to_array(btrim(claimant_name), '\\s+'), 1)-1],
                    ' '
                  )
                ELSE NULL
              END,
              claimant_last_name = CASE
                WHEN claimant_last_name IS NOT NULL AND btrim(claimant_last_name) <> '' THEN claimant_last_name
                WHEN claimant_name IS NULL OR btrim(claimant_name) = '' THEN NULL
                WHEN position(',' in claimant_name) > 0 THEN btrim(split_part(claimant_name, ',', 1))
                WHEN array_length(regexp_split_to_array(btrim(claimant_name), '\\s+'), 1) >= 2 THEN
                  (regexp_split_to_array(btrim(claimant_name), '\\s+'))[array_length(regexp_split_to_array(btrim(claimant_name), '\\s+'), 1)]
                ELSE btrim(claimant_name)
              END
            WHERE claimant_name IS NOT NULL;
            """
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('claim', 'claimant_last_name')
    op.drop_column('claim', 'claimant_first_name')
