"""Make billable notes Text instead of String(255)

Revision ID: 182b817ab9c2
Revises: 247905af875c
Create Date: 2026-02-13 16:42:29.122502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '182b817ab9c2'
down_revision: Union[str, Sequence[str], None] = '247905af875c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_treating_provider_claim_id'), table_name='claim_treating_provider')
    op.drop_index(op.f('ix_claim_treating_provider_provider_id'), table_name='claim_treating_provider')
    op.drop_table('claim_treating_provider')
    op.drop_index(op.f('ix_claim_surgery_date_claim_id'), table_name='claim_surgery_date')
    op.drop_table('claim_surgery_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_surgery_date',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('surgery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('claim_surgery_date_claim_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_surgery_date_pkey'))
    )
    op.create_index(op.f('ix_claim_surgery_date_claim_id'), 'claim_surgery_date', ['claim_id'], unique=False)
    op.create_table('claim_treating_provider',
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('claim_treating_provider_claim_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('claim_treating_provider_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'provider_id', name=op.f('claim_treating_provider_pkey'))
    )
    op.create_index(op.f('ix_claim_treating_provider_provider_id'), 'claim_treating_provider', ['provider_id'], unique=False)
    op.create_index(op.f('ix_claim_treating_provider_claim_id'), 'claim_treating_provider', ['claim_id'], unique=False)
    # ### end Alembic commands ###
