"""Add email and clarity AI settings fields

Revision ID: 247905af875c
Revises: 7c12658c6a01
Create Date: 2026-02-13 15:48:26.280553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247905af875c'
down_revision: Union[str, Sequence[str], None] = '7c12658c6a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('settings', sa.Column('smtp_encryption', sa.String(length=10), nullable=True))
    op.add_column('settings', sa.Column('smtp_username', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('email_from', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('clarity_enabled', sa.Boolean(), nullable=True))
    op.add_column('settings', sa.Column('clarity_model', sa.String(length=255), nullable=True))
    op.add_column('settings', sa.Column('clarity_temperature', sa.Float(), nullable=True))
    op.add_column('settings', sa.Column('clarity_summary_prompt', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('clarity_plan_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'clarity_plan_prompt')
    op.drop_column('settings', 'clarity_summary_prompt')
    op.drop_column('settings', 'clarity_temperature')
    op.drop_column('settings', 'clarity_model')
    op.drop_column('settings', 'clarity_enabled')
    op.drop_column('settings', 'email_from')
    op.drop_column('settings', 'smtp_password')
    op.drop_column('settings', 'smtp_username')
    op.drop_column('settings', 'smtp_encryption')
    op.drop_column('settings', 'smtp_port')
    op.drop_column('settings', 'smtp_host')
    # ### end Alembic commands ###
