"""Add opened_at and closed_at to Claim

Revision ID: 29ff72b70732
Revises: e632acd507c8
Create Date: 2026-02-15 19:57:32.916821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ff72b70732'
down_revision: Union[str, Sequence[str], None] = 'e632acd507c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('opened_at', sa.Date(), nullable=True))
    op.add_column('claim', sa.Column('closed_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'closed_at')
    op.drop_column('claim', 'opened_at')
    op.create_table('claim_surgery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('surgery_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('claim_surgery_claim_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_surgery_pkey'))
    )
    op.create_index(op.f('ix_claim_surgery_claim_id'), 'claim_surgery', ['claim_id'], unique=False)
    op.create_table('claim_treating_provider',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('claim_treating_provider_claim_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('claim_treating_provider_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_treating_provider_pkey'))
    )
    op.create_index(op.f('ix_claim_treating_provider_provider_id'), 'claim_treating_provider', ['provider_id'], unique=False)
    op.create_index(op.f('ix_claim_treating_provider_claim_id'), 'claim_treating_provider', ['claim_id'], unique=False)
    # ### end Alembic commands ###
