"""Add IW representation and attorney fields to Claim

Revision ID: 4b1b8ebfa682
Revises: 9b2e818fb54e
Create Date: 2026-02-27 17:40:15.391304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1b8ebfa682'
down_revision: Union[str, Sequence[str], None] = '9b2e818fb54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('claim', sa.Column('is_represented', sa.Boolean(), nullable=True))
    op.add_column('claim', sa.Column('attorney_name', sa.String(length=255), nullable=True))
    op.add_column('claim', sa.Column('attorney_firm', sa.String(length=255), nullable=True))
    op.add_column('claim', sa.Column('attorney_phone', sa.String(length=50), nullable=True))
    op.add_column('claim', sa.Column('attorney_email', sa.String(length=255), nullable=True))
    op.add_column('claim', sa.Column('attorney_contact_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('claim', 'attorney_contact_allowed')
    op.drop_column('claim', 'attorney_email')
    op.drop_column('claim', 'attorney_phone')
    op.drop_column('claim', 'attorney_firm')
    op.drop_column('claim', 'attorney_name')
    op.drop_column('claim', 'is_represented')
    # ### end Alembic commands ###
