"""carrier rates sync

Revision ID: 7adb3e8e08b0
Revises: fc310f7c3872
Create Date: 2025-12-25 08:48:09.945039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adb3e8e08b0'
down_revision: Union[str, Sequence[str], None] = 'fc310f7c3872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('claim', 'injured_body_part',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_contact_contact_role_id'), table_name='contact')
    op.drop_constraint(op.f('contact_contact_role_id_fkey'), 'contact', type_='foreignkey')
    op.create_foreign_key(None, 'contact', 'contact_role', ['contact_role_id'], ['id'])
    op.drop_constraint(op.f('contact_role_label_key'), 'contact_role', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('contact_role_label_key'), 'contact_role', ['label'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'contact', type_='foreignkey')
    op.create_foreign_key(op.f('contact_contact_role_id_fkey'), 'contact', 'contact_role', ['contact_role_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_contact_contact_role_id'), 'contact', ['contact_role_id'], unique=False)
    op.alter_column('claim', 'injured_body_part',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
