"""add provider organization

Revision ID: 957ca176e0c1
Revises: 3ff94d74a6b5
Create Date: 2026-01-29 17:49:06.190254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957ca176e0c1'
down_revision: Union[str, Sequence[str], None] = '3ff94d74a6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_treating_provider_claim_id'), table_name='claim_treating_provider')
    op.drop_index(op.f('ix_claim_treating_provider_provider_id'), table_name='claim_treating_provider')
    op.drop_table('claim_treating_provider')
    op.add_column('provider', sa.Column('organization', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'organization')
    op.create_table('claim_treating_provider',
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('claim_treating_provider_claim_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('claim_treating_provider_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'provider_id', name=op.f('claim_treating_provider_pkey'))
    )
    op.create_index(op.f('ix_claim_treating_provider_provider_id'), 'claim_treating_provider', ['provider_id'], unique=False)
    op.create_index(op.f('ix_claim_treating_provider_claim_id'), 'claim_treating_provider', ['claim_id'], unique=False)
    # ### end Alembic commands ###
