"""Add report_id to invoice

Revision ID: a0d9e44a2abe
Revises: 0d49474106c3
Create Date: 2026-02-13 19:38:43.752503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d9e44a2abe'
down_revision: Union[str, Sequence[str], None] = '0d49474106c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice', sa.Column('report_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice', 'report', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice', type_='foreignkey')
    op.drop_column('invoice', 'report_id')
    # ### end Alembic commands ###
