"""add specialty to provider

Revision ID: bb22f4251c37
Revises: 1c3dffb05fee
Create Date: 2026-01-02 16:46:07.037803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb22f4251c37'
down_revision: Union[str, Sequence[str], None] = '1c3dffb05fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('provider', sa.Column('specialty', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('provider', 'specialty')
    # ### end Alembic commands ###
