"""add initial next appt notes

Revision ID: ec9f5c7c243e
Revises: 1904f6126fa5
Create Date: 2026-01-29 16:46:05.987188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec9f5c7c243e'
down_revision: Union[str, Sequence[str], None] = '1904f6126fa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_surgery_claim_id'), table_name='claim_surgery')
    op.drop_index(op.f('ix_claim_surgery_surgery_date'), table_name='claim_surgery')
    op.drop_table('claim_surgery')
    op.drop_index(op.f('ix_claim_treating_provider_claim_id'), table_name='claim_treating_provider')
    op.drop_table('claim_treating_provider')
    op.add_column('report', sa.Column('initial_next_appt_notes', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'initial_next_appt_notes')
    op.create_table('claim_treating_provider',
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('claim_treating_provider_claim_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['provider.id'], name=op.f('claim_treating_provider_provider_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('claim_id', 'provider_id', name=op.f('claim_treating_provider_pkey'))
    )
    op.create_index(op.f('ix_claim_treating_provider_claim_id'), 'claim_treating_provider', ['claim_id'], unique=False)
    op.create_table('claim_surgery',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('claim_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('surgery_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claim.id'], name=op.f('claim_surgery_claim_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('claim_surgery_pkey'))
    )
    op.create_index(op.f('ix_claim_surgery_surgery_date'), 'claim_surgery', ['surgery_date'], unique=False)
    op.create_index(op.f('ix_claim_surgery_claim_id'), 'claim_surgery', ['claim_id'], unique=False)
    # ### end Alembic commands ###
